language: python
python:
  - "2.7"
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django111
  # - TOX_ENV=py35-django18
  # - TOX_ENV=py35-django111
install:
  - pip install tox
notifications:
  email:
    - jason.louard.ward@gmail.com
script: tox -e $TOX_ENV
